<Project>
  <PropertyGroup>
    <Product>NDI Configurator PC Agent</Product>
    <Authors>John Lightfoot</Authors>
    <Company>John Lightfoot</Company>
    <Version>0.6.1</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ReleaseChannel>Production</ReleaseChannel>
    <Copyright>Copyright © 2026 John Lightfoot. All rights reserved. Proprietary software; free for non-commercial use.</Copyright>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/JohnDevAc/Kiloview-PC-Onboarding</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="License" Value="Proprietary software; free for non-commercial use" />
  </ItemGroup>
</Project>
